//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class CheckboxGroup : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.FieldContainer
    {
        
        public string _allowBlank_default = "true";
        
        public string _blankText_default = "\"You must select at least one item in this group\"";
        
        public string _columns_default = "\'auto\'";
        
        public string _componentCls_default = "Ext.baseCSSPrefix + \'form-checkboxgroup\'";
        
        public string _defaultType_default = "\'checkboxfield\'";
        
        public string _layout_default = "\'checkboxgroup\'";
        
        public string _vertical_default = "false";
        
        public object allowBlank
        {
            get
            {
                return this.attributes["allowBlank"];
            }
            set
            {
                this.attributes["allowBlank"] = value;
            }
        }
        
        public object blankText
        {
            get
            {
                return this.attributes["blankText"];
            }
            set
            {
                this.attributes["blankText"] = value;
            }
        }
        
        public object columns
        {
            get
            {
                return this.attributes["columns"];
            }
            set
            {
                this.attributes["columns"] = value;
            }
        }
        
        public object componentCls
        {
            get
            {
                return this.attributes["componentCls"];
            }
            set
            {
                this.attributes["componentCls"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object vertical
        {
            get
            {
                return this.attributes["vertical"];
            }
            set
            {
                this.attributes["vertical"] = value;
            }
        }
        
        public class MultiType_allowBlank
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_blankText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_columns
        {
            
            public @string _string_type;
            
            public @double _double_type;
            
            public List<double> _List<double>_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public List<double> AsNumber[]
            {
                get
                {
                    return this._List<double>_type;
                }
                set
                {
                    this._List<double>_type = value;
                }
            }
        }
        
        public class MultiType_componentCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_defaultType
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_items
        {
            
            public System.Collections.Generic.List<object> _System.Collections.Generic.List`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public System.Collections.Generic.List<object> AsExt.form.field.Checkbox[]
            {
                get
                {
                    return this._System.Collections.Generic.List`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]_type;
                }
                set
                {
                    this._System.Collections.Generic.List`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]_type = value;
                }
            }
            
            public List<System.Object> AsObject[]
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
        }
        
        public class MultiType_layout
        {
            
            public object _System.Object_type;
            
            public object _System.Object_type;
            
            public object AsExt.enums.Layout
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_vertical
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
