//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.dd
{
    using System;
    
    
    public partial class DragZone : zzProject.ExtJSNet.ExtJS.Classes.Ext.dd.DragSource
    {
        
        public object containerScroll
        {
            get
            {
                return this.attributes["containerScroll"];
            }
            set
            {
                this.attributes["containerScroll"] = value;
            }
        }
        
        public object scrollEl
        {
            get
            {
                return this.attributes["scrollEl"];
            }
            set
            {
                this.attributes["scrollEl"] = value;
            }
        }
        
        public class MultiType_containerScroll
        {
            
            public object _System.Object_type;
            
            public @bool _bool_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_scrollEl
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsHTMLElement
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public object AsExt.dom.Element
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
