//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.picker
{
    using System;
    
    
    public partial class Date : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _ariaTitle_default = "\'Date Picker: {0}\'";
        
        public string _ariaTitleDateFormat_default = "\'F d, Y\'";
        
        public string _baseCls_default = "\'x-datepicker\'";
        
        public string _border_default = "true";
        
        public string _disableAnim_default = "false";
        
        public string _disabledCellCls_default = "\'x-datepicker-disabled\'";
        
        public string _disabledDatesRE_default = "null";
        
        public string _disabledDatesText_default = "\'Disabled\'";
        
        public string _disabledDays_default = "null";
        
        public string _disabledDaysText_default = "\'Disabled\'";
        
        public string _focusOnShow_default = "false";
        
        public string _longDayFormat_default = "\'F d, Y\'";
        
        public string _maxDate_default = "null";
        
        public string _maxText_default = "\'This date is after the maximum date\'";
        
        public string _minDate_default = "null";
        
        public string _minText_default = "\'This date is before the minimum date\'";
        
        public string _monthYearFormat_default = "\'F Y\'";
        
        public string _monthYearText_default = "\'Choose a month (Control+Up/Down to move years)\'";
        
        public string _nextText_default = "\'Next Month (Control+Right)\'";
        
        public string _prevText_default = "\'Previous Month (Control+Left)\'";
        
        public string _renderTpl_default = "\'{%this.renderContent(out,values)%}\'";
        
        public string _selectedCls_default = "\'x-datepicker-selected\'";
        
        public string _showToday_default = "true";
        
        public string _startDay_default = "undefined";
        
        public string _todayText_default = "\'Today\'";
        
        public string _todayTip_default = "\'{0} (Spacebar)\'";
        
        public object ariaTitle
        {
            get
            {
                return this.attributes["ariaTitle"];
            }
            set
            {
                this.attributes["ariaTitle"] = value;
            }
        }
        
        public object ariaTitleDateFormat
        {
            get
            {
                return this.attributes["ariaTitleDateFormat"];
            }
            set
            {
                this.attributes["ariaTitleDateFormat"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object border
        {
            get
            {
                return this.attributes["border"];
            }
            set
            {
                this.attributes["border"] = value;
            }
        }
        
        public object dayNames
        {
            get
            {
                return this.attributes["dayNames"];
            }
            set
            {
                this.attributes["dayNames"] = value;
            }
        }
        
        public object disableAnim
        {
            get
            {
                return this.attributes["disableAnim"];
            }
            set
            {
                this.attributes["disableAnim"] = value;
            }
        }
        
        public object disabledCellCls
        {
            get
            {
                return this.attributes["disabledCellCls"];
            }
            set
            {
                this.attributes["disabledCellCls"] = value;
            }
        }
        
        public object disabledDates
        {
            get
            {
                return this.attributes["disabledDates"];
            }
            set
            {
                this.attributes["disabledDates"] = value;
            }
        }
        
        public object disabledDatesRE
        {
            get
            {
                return this.attributes["disabledDatesRE"];
            }
            set
            {
                this.attributes["disabledDatesRE"] = value;
            }
        }
        
        public object disabledDatesText
        {
            get
            {
                return this.attributes["disabledDatesText"];
            }
            set
            {
                this.attributes["disabledDatesText"] = value;
            }
        }
        
        public object disabledDays
        {
            get
            {
                return this.attributes["disabledDays"];
            }
            set
            {
                this.attributes["disabledDays"] = value;
            }
        }
        
        public object disabledDaysText
        {
            get
            {
                return this.attributes["disabledDaysText"];
            }
            set
            {
                this.attributes["disabledDaysText"] = value;
            }
        }
        
        public object focusOnShow
        {
            get
            {
                return this.attributes["focusOnShow"];
            }
            set
            {
                this.attributes["focusOnShow"] = value;
            }
        }
        
        public object format
        {
            get
            {
                return this.attributes["format"];
            }
            set
            {
                this.attributes["format"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object keyNavConfig
        {
            get
            {
                return this.attributes["keyNavConfig"];
            }
            set
            {
                this.attributes["keyNavConfig"] = value;
            }
        }
        
        public object longDayFormat
        {
            get
            {
                return this.attributes["longDayFormat"];
            }
            set
            {
                this.attributes["longDayFormat"] = value;
            }
        }
        
        public object maxDate
        {
            get
            {
                return this.attributes["maxDate"];
            }
            set
            {
                this.attributes["maxDate"] = value;
            }
        }
        
        public object maxText
        {
            get
            {
                return this.attributes["maxText"];
            }
            set
            {
                this.attributes["maxText"] = value;
            }
        }
        
        public object minDate
        {
            get
            {
                return this.attributes["minDate"];
            }
            set
            {
                this.attributes["minDate"] = value;
            }
        }
        
        public object minText
        {
            get
            {
                return this.attributes["minText"];
            }
            set
            {
                this.attributes["minText"] = value;
            }
        }
        
        public object monthNames
        {
            get
            {
                return this.attributes["monthNames"];
            }
            set
            {
                this.attributes["monthNames"] = value;
            }
        }
        
        public object monthYearFormat
        {
            get
            {
                return this.attributes["monthYearFormat"];
            }
            set
            {
                this.attributes["monthYearFormat"] = value;
            }
        }
        
        public object monthYearText
        {
            get
            {
                return this.attributes["monthYearText"];
            }
            set
            {
                this.attributes["monthYearText"] = value;
            }
        }
        
        public object nextText
        {
            get
            {
                return this.attributes["nextText"];
            }
            set
            {
                this.attributes["nextText"] = value;
            }
        }
        
        public object prevText
        {
            get
            {
                return this.attributes["prevText"];
            }
            set
            {
                this.attributes["prevText"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object selectedCls
        {
            get
            {
                return this.attributes["selectedCls"];
            }
            set
            {
                this.attributes["selectedCls"] = value;
            }
        }
        
        public object showToday
        {
            get
            {
                return this.attributes["showToday"];
            }
            set
            {
                this.attributes["showToday"] = value;
            }
        }
        
        public object startDay
        {
            get
            {
                return this.attributes["startDay"];
            }
            set
            {
                this.attributes["startDay"] = value;
            }
        }
        
        public object todayText
        {
            get
            {
                return this.attributes["todayText"];
            }
            set
            {
                this.attributes["todayText"] = value;
            }
        }
        
        public object todayTip
        {
            get
            {
                return this.attributes["todayTip"];
            }
            set
            {
                this.attributes["todayTip"] = value;
            }
        }
        
        public class MultiType_ariaTitle
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_ariaTitleDateFormat
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_baseCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_border
        {
            
            public @double _double_type;
            
            public @string _string_type;
            
            public @bool _bool_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_dayNames
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_disableAnim
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_disabledCellCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_disabledDates
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_disabledDatesRE
        {
            
            public System.Text.RegularExpressions.Regex _System.Text.RegularExpressions.Regex_type;
            
            public System.Text.RegularExpressions.Regex AsRegExp
            {
                get
                {
                    return this._System.Text.RegularExpressions.Regex_type;
                }
                set
                {
                    this._System.Text.RegularExpressions.Regex_type = value;
                }
            }
        }
        
        public class MultiType_disabledDatesText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_disabledDays
        {
            
            public List<double> _List<double>_type;
            
            public List<double> AsNumber[]
            {
                get
                {
                    return this._List<double>_type;
                }
                set
                {
                    this._List<double>_type = value;
                }
            }
        }
        
        public class MultiType_disabledDaysText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_focusOnShow
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_format
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_handler
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_keyNavConfig
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_longDayFormat
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_maxDate
        {
            
            public System.DateTime _System.DateTime_type;
            
            public System.DateTime AsDate
            {
                get
                {
                    return this._System.DateTime_type;
                }
                set
                {
                    this._System.DateTime_type = value;
                }
            }
        }
        
        public class MultiType_maxText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_minDate
        {
            
            public System.DateTime _System.DateTime_type;
            
            public System.DateTime AsDate
            {
                get
                {
                    return this._System.DateTime_type;
                }
                set
                {
                    this._System.DateTime_type = value;
                }
            }
        }
        
        public class MultiType_minText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_monthNames
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_monthYearFormat
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_monthYearText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_nextText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_prevText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_renderTpl
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_scope
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_selectedCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_showToday
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_startDay
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_todayText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_todayTip
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
