//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class FileButton : zzProject.ExtJSNet.ExtJS.Classes.Ext.button.Button
    {
        
        public string _cls_default = "Ext.baseCSSPrefix + \'form-file-btn\'";
        
        public string _preventDefault_default = "false";
        
        public string _renderTpl_default = @"['<span id=""{id}-btnWrap"" class=""{baseCls}-wrap', '<tpl if=""splitCls""> {splitCls}</tpl>', '{childElCls}"" unselectable=""on"">', '<span id=""{id}-btnEl"" class=""{baseCls}-button"">', '<span id=""{id}-btnInnerEl"" class=""{baseCls}-inner {innerCls}', '{childElCls}"" unselectable=""on"">', '{text}', '</span>', '<span role=""img"" id=""{id}-btnIconEl"" class=""{baseCls}-icon-el {iconCls}', '{childElCls} {glyphCls}"" unselectable=""on"" style=""', '<tpl if=""iconUrl"">background-image:url({iconUrl});</tpl>', '<tpl if=""glyph && glyphFontFamily"">font-family:{glyphFontFamily};</tpl>"">', '<tpl if=""glyph"">&#{glyph};</tpl><tpl if=""iconCls || iconUrl"">&#160;</tpl>', '</span>', '</span>', '</span>', '<input id=""{id}-fileInputEl"" class=""{childElCls} {inputCls}"" type=""file"" size=""1"" name=""{inputName}"">']";
        
        public object cls
        {
            get
            {
                return this.attributes["cls"];
            }
            set
            {
                this.attributes["cls"] = value;
            }
        }
        
        public object preventDefault
        {
            get
            {
                return this.attributes["preventDefault"];
            }
            set
            {
                this.attributes["preventDefault"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public class MultiType_cls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_preventDefault
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_renderTpl
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
    }
}
