//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.boxOverflow
{
    using System;
    
    
    public partial class Menu : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.boxOverflow.None
    {
        
        public object triggerButtonCls
        {
            get
            {
                return this.attributes["triggerButtonCls"];
            }
            set
            {
                this.attributes["triggerButtonCls"] = value;
            }
        }
        
        public class MultiType_triggerButtonCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
