//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class Class
    {
        
        public object alias
        {
            get
            {
                return this.attributes["alias"];
            }
            set
            {
                this.attributes["alias"] = value;
            }
        }
        
        public object alternateClassName
        {
            get
            {
                return this.attributes["alternateClassName"];
            }
            set
            {
                this.attributes["alternateClassName"] = value;
            }
        }
        
        public object config
        {
            get
            {
                return this.attributes["config"];
            }
            set
            {
                this.attributes["config"] = value;
            }
        }
        
        public object extend
        {
            get
            {
                return this.attributes["extend"];
            }
            set
            {
                this.attributes["extend"] = value;
            }
        }
        
        public object inheritableStatics
        {
            get
            {
                return this.attributes["inheritableStatics"];
            }
            set
            {
                this.attributes["inheritableStatics"] = value;
            }
        }
        
        public object mixins
        {
            get
            {
                return this.attributes["mixins"];
            }
            set
            {
                this.attributes["mixins"] = value;
            }
        }
        
        public object requires
        {
            get
            {
                return this.attributes["requires"];
            }
            set
            {
                this.attributes["requires"] = value;
            }
        }
        
        public object singleton
        {
            get
            {
                return this.attributes["singleton"];
            }
            set
            {
                this.attributes["singleton"] = value;
            }
        }
        
        public object statics
        {
            get
            {
                return this.attributes["statics"];
            }
            set
            {
                this.attributes["statics"] = value;
            }
        }
        
        public object uses
        {
            get
            {
                return this.attributes["uses"];
            }
            set
            {
                this.attributes["uses"] = value;
            }
        }
        
        public class MultiType_alias
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_alternateClassName
        {
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_config
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_extend
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_inheritableStatics
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_mixins
        {
            
            public List<string> _List<string>_type;
            
            public object _System.Object_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_requires
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_singleton
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_statics
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_uses
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
    }
}
