//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Bar : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Cartesian
    {
        
        public string _column_default = "false";
        
        public string _groupGutter_default = "38.2";
        
        public string _gutter_default = "38.2";
        
        public string _style_default = "{}";
        
        public string _type_default = "\'bar\'";
        
        public string _xPadding_default = "0";
        
        public string _yPadding_default = "10";
        
        public object column
        {
            get
            {
                return this.attributes["column"];
            }
            set
            {
                this.attributes["column"] = value;
            }
        }
        
        public object groupGutter
        {
            get
            {
                return this.attributes["groupGutter"];
            }
            set
            {
                this.attributes["groupGutter"] = value;
            }
        }
        
        public object gutter
        {
            get
            {
                return this.attributes["gutter"];
            }
            set
            {
                this.attributes["gutter"] = value;
            }
        }
        
        public object stacked
        {
            get
            {
                return this.attributes["stacked"];
            }
            set
            {
                this.attributes["stacked"] = value;
            }
        }
        
        public object style
        {
            get
            {
                return this.attributes["style"];
            }
            set
            {
                this.attributes["style"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object xPadding
        {
            get
            {
                return this.attributes["xPadding"];
            }
            set
            {
                this.attributes["xPadding"] = value;
            }
        }
        
        public object yPadding
        {
            get
            {
                return this.attributes["yPadding"];
            }
            set
            {
                this.attributes["yPadding"] = value;
            }
        }
        
        public class MultiType_column
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_groupGutter
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_gutter
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_stacked
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_style
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_type
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_xPadding
        {
            
            public @double _double_type;
            
            public object _System.Object_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_yPadding
        {
            
            public @double _double_type;
            
            public object _System.Object_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
