//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.view
{
    using System;
    
    
    public partial class BoundList : zzProject.ExtJSNet.ExtJS.Classes.Ext.view.View
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'boundlist\'";
        
        public string _componentLayout_default = "\'boundlist\'";
        
        public string _deferInitialRefresh_default = "false";
        
        public string _displayField_default = "\"\"";
        
        public string _itemCls_default = "Ext.baseCSSPrefix + \'boundlist-item\'";
        
        public string _pageSize_default = "0";
        
        public string _renderTpl_default = "\'{%this.renderContent(out,values)%}\'";
        
        public string _shadow_default = "false";
        
        public string _trackOver_default = "true";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object deferInitialRefresh
        {
            get
            {
                return this.attributes["deferInitialRefresh"];
            }
            set
            {
                this.attributes["deferInitialRefresh"] = value;
            }
        }
        
        public object displayField
        {
            get
            {
                return this.attributes["displayField"];
            }
            set
            {
                this.attributes["displayField"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object pageSize
        {
            get
            {
                return this.attributes["pageSize"];
            }
            set
            {
                this.attributes["pageSize"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object shadow
        {
            get
            {
                return this.attributes["shadow"];
            }
            set
            {
                this.attributes["shadow"] = value;
            }
        }
        
        public object tpl
        {
            get
            {
                return this.attributes["tpl"];
            }
            set
            {
                this.attributes["tpl"] = value;
            }
        }
        
        public object trackOver
        {
            get
            {
                return this.attributes["trackOver"];
            }
            set
            {
                this.attributes["trackOver"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_componentLayout
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_deferInitialRefresh
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_displayField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_itemCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_pageSize
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_renderTpl
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_shadow
        {
            
            public @string _string_type;
            
            public @bool _bool_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_tpl
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_trackOver
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
