//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tab
{
    using System;
    
    
    public partial class Bar : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Header
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'tab-bar\'";
        
        public string _plain_default = "false";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object maxTabWidth
        {
            get
            {
                return this.attributes["maxTabWidth"];
            }
            set
            {
                this.attributes["maxTabWidth"] = value;
            }
        }
        
        public object minTabWidth
        {
            get
            {
                return this.attributes["minTabWidth"];
            }
            set
            {
                this.attributes["minTabWidth"] = value;
            }
        }
        
        public object plain
        {
            get
            {
                return this.attributes["plain"];
            }
            set
            {
                this.attributes["plain"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_maxTabWidth
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_minTabWidth
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_plain
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
