//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.state
{
    using System;
    
    
    public partial class CookieProvider : zzProject.ExtJSNet.ExtJS.Classes.Ext.state.Provider
    {
        
        public string _secure_default = "false";
        
        public object domain
        {
            get
            {
                return this.attributes["domain"];
            }
            set
            {
                this.attributes["domain"] = value;
            }
        }
        
        public object expires
        {
            get
            {
                return this.attributes["expires"];
            }
            set
            {
                this.attributes["expires"] = value;
            }
        }
        
        public object path
        {
            get
            {
                return this.attributes["path"];
            }
            set
            {
                this.attributes["path"] = value;
            }
        }
        
        public object secure
        {
            get
            {
                return this.attributes["secure"];
            }
            set
            {
                this.attributes["secure"] = value;
            }
        }
        
        public class MultiType_domain
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_expires
        {
            
            public System.DateTime _System.DateTime_type;
            
            public System.DateTime AsDate
            {
                get
                {
                    return this._System.DateTime_type;
                }
                set
                {
                    this._System.DateTime_type = value;
                }
            }
        }
        
        public class MultiType_path
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_secure
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
