//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.resizer
{
    using System;
    
    
    public partial class Splitter : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'splitter\'";
        
        public string _collapseOnDblClick_default = "true";
        
        public string _collapseTarget_default = "\'next\'";
        
        public string _collapsible_default = "false";
        
        public string _defaultSplitMax_default = "1000";
        
        public string _defaultSplitMin_default = "40";
        
        public string _renderTpl_default = "[\'<tpl if=\"collapsible===true\">\', \'<div id=\"{id}-collapseEl\" class=\"\', Ext.baseCS" +
            "SPrefix, \'collapse-el \', Ext.baseCSSPrefix, \'layout-split-{collapseDir}{childElC" +
            "ls}\">&#160;\', \'</div>\', \'</tpl>\']";
        
        public string _size_default = "5";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object collapseOnDblClick
        {
            get
            {
                return this.attributes["collapseOnDblClick"];
            }
            set
            {
                this.attributes["collapseOnDblClick"] = value;
            }
        }
        
        public object collapseTarget
        {
            get
            {
                return this.attributes["collapseTarget"];
            }
            set
            {
                this.attributes["collapseTarget"] = value;
            }
        }
        
        public object collapsedCls
        {
            get
            {
                return this.attributes["collapsedCls"];
            }
            set
            {
                this.attributes["collapsedCls"] = value;
            }
        }
        
        public object collapsible
        {
            get
            {
                return this.attributes["collapsible"];
            }
            set
            {
                this.attributes["collapsible"] = value;
            }
        }
        
        public object defaultSplitMax
        {
            get
            {
                return this.attributes["defaultSplitMax"];
            }
            set
            {
                this.attributes["defaultSplitMax"] = value;
            }
        }
        
        public object defaultSplitMin
        {
            get
            {
                return this.attributes["defaultSplitMin"];
            }
            set
            {
                this.attributes["defaultSplitMin"] = value;
            }
        }
        
        public object performCollapse
        {
            get
            {
                return this.attributes["performCollapse"];
            }
            set
            {
                this.attributes["performCollapse"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object size
        {
            get
            {
                return this.attributes["size"];
            }
            set
            {
                this.attributes["size"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_collapseOnDblClick
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_collapseTarget
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsExt.panel.Panel
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_collapsedCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_collapsible
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_defaultSplitMax
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_defaultSplitMin
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_performCollapse
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_renderTpl
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_size
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
    }
}
