//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.feature
{
    using System;
    
    
    public partial class AbstractSummary : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.feature.Feature
    {
        
        public string _remoteRoot_default = "undefined";
        
        public string _showSummaryRow_default = "true";
        
        public object remoteRoot
        {
            get
            {
                return this.attributes["remoteRoot"];
            }
            set
            {
                this.attributes["remoteRoot"] = value;
            }
        }
        
        public object showSummaryRow
        {
            get
            {
                return this.attributes["showSummaryRow"];
            }
            set
            {
                this.attributes["showSummaryRow"] = value;
            }
        }
        
        public class MultiType_remoteRoot
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_showSummaryRow
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
