//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class ElementLoader : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _autoLoad_default = "false";
        
        public string _loadMask_default = "false";
        
        public string _scripts_default = "false";
        
        public object ajaxOptions
        {
            get
            {
                return this.attributes["ajaxOptions"];
            }
            set
            {
                this.attributes["ajaxOptions"] = value;
            }
        }
        
        public object autoLoad
        {
            get
            {
                return this.attributes["autoLoad"];
            }
            set
            {
                this.attributes["autoLoad"] = value;
            }
        }
        
        public object baseParams
        {
            get
            {
                return this.attributes["baseParams"];
            }
            set
            {
                this.attributes["baseParams"] = value;
            }
        }
        
        public object callback
        {
            get
            {
                return this.attributes["callback"];
            }
            set
            {
                this.attributes["callback"] = value;
            }
        }
        
        public object failure
        {
            get
            {
                return this.attributes["failure"];
            }
            set
            {
                this.attributes["failure"] = value;
            }
        }
        
        public object loadMask
        {
            get
            {
                return this.attributes["loadMask"];
            }
            set
            {
                this.attributes["loadMask"] = value;
            }
        }
        
        public object _params
        {
            get
            {
                return this.attributes["params"];
            }
            set
            {
                this.attributes["params"] = value;
            }
        }
        
        public object renderer
        {
            get
            {
                return this.attributes["renderer"];
            }
            set
            {
                this.attributes["renderer"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object scripts
        {
            get
            {
                return this.attributes["scripts"];
            }
            set
            {
                this.attributes["scripts"] = value;
            }
        }
        
        public object success
        {
            get
            {
                return this.attributes["success"];
            }
            set
            {
                this.attributes["success"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public class MultiType_ajaxOptions
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_autoLoad
        {
            
            public @bool _bool_type;
            
            public object _System.Object_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_baseParams
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_callback
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_failure
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_loadMask
        {
            
            public @bool _bool_type;
            
            public @string _string_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_params
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_renderer
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_scope
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_scripts
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_success
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_target
        {
            
            public object _System.Object_type;
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public object AsHTMLElement
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public object AsExt.Element
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_url
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
