//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart
{
    using System;
    
    
    public partial class Highlight : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _highlight_default = "false";
        
        public object highlight
        {
            get
            {
                return this.attributes["highlight"];
            }
            set
            {
                this.attributes["highlight"] = value;
            }
        }
        
        public class MultiType_highlight
        {
            
            public @bool _bool_type;
            
            public object _System.Object_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
