//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class Panel : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _layout_default = "\'anchor\'";
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object pollForChanges
        {
            get
            {
                return this.attributes["pollForChanges"];
            }
            set
            {
                this.attributes["pollForChanges"] = value;
            }
        }
        
        public object pollInterval
        {
            get
            {
                return this.attributes["pollInterval"];
            }
            set
            {
                this.attributes["pollInterval"] = value;
            }
        }
        
        public class MultiType_layout
        {
            
            public object _System.Object_type;
            
            public object _System.Object_type;
            
            public object AsExt.enums.Layout
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_pollForChanges
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_pollInterval
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
    }
}
