//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.button
{
    using System;
    
    
    public partial class Cycle : zzProject.ExtJSNet.ExtJS.Classes.Ext.button.Split
    {
        
        public string _prependText_default = "\'\'";
        
        public string _showText_default = "false";
        
        public object changeHandler
        {
            get
            {
                return this.attributes["changeHandler"];
            }
            set
            {
                this.attributes["changeHandler"] = value;
            }
        }
        
        public object forceGlyph
        {
            get
            {
                return this.attributes["forceGlyph"];
            }
            set
            {
                this.attributes["forceGlyph"] = value;
            }
        }
        
        public object forceIcon
        {
            get
            {
                return this.attributes["forceIcon"];
            }
            set
            {
                this.attributes["forceIcon"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object prependText
        {
            get
            {
                return this.attributes["prependText"];
            }
            set
            {
                this.attributes["prependText"] = value;
            }
        }
        
        public object showText
        {
            get
            {
                return this.attributes["showText"];
            }
            set
            {
                this.attributes["showText"] = value;
            }
        }
        
        public class MultiType_changeHandler
        {
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_forceGlyph
        {
            
            public @double _double_type;
            
            public @string _string_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_forceIcon
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_items
        {
            
            public List<System.Object> _List<System.Object>_type;
            
            public List<System.Object> AsObject[]
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
        }
        
        public class MultiType_prependText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_showText
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
