//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid
{
    using System;
    
    
    public partial class RowEditorButtons : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _frame_default = "true";
        
        public string _shrinkWrap_default = "true";
        
        public object frame
        {
            get
            {
                return this.attributes["frame"];
            }
            set
            {
                this.attributes["frame"] = value;
            }
        }
        
        public object shrinkWrap
        {
            get
            {
                return this.attributes["shrinkWrap"];
            }
            set
            {
                this.attributes["shrinkWrap"] = value;
            }
        }
        
        public class MultiType_frame
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_shrinkWrap
        {
            
            public @bool _bool_type;
            
            public @double _double_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
    }
}
