//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class HtmlEditor : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.FieldContainer
    {
        
        public string _componentLayout_default = "\'htmleditor\'";
        
        public string _createLinkText_default = "\'Please enter the URL for the link:\'";
        
        public string _defaultLinkValue_default = "\'http://\'";
        
        public string _enableAlignments_default = "true";
        
        public string _enableColors_default = "true";
        
        public string _enableFont_default = "true";
        
        public string _enableFontSize_default = "true";
        
        public string _enableFormat_default = "true";
        
        public string _enableLinks_default = "true";
        
        public string _enableLists_default = "true";
        
        public string _enableSourceEdit_default = "true";
        
        public string _fontFamilies_default = "[\'Arial\', \'Courier New\', \'Tahoma\', \'Times New Roman\', \'Verdana\']";
        
        public object afterIFrameTpl
        {
            get
            {
                return this.attributes["afterIFrameTpl"];
            }
            set
            {
                this.attributes["afterIFrameTpl"] = value;
            }
        }
        
        public object afterTextAreaTpl
        {
            get
            {
                return this.attributes["afterTextAreaTpl"];
            }
            set
            {
                this.attributes["afterTextAreaTpl"] = value;
            }
        }
        
        public object beforeIFrameTpl
        {
            get
            {
                return this.attributes["beforeIFrameTpl"];
            }
            set
            {
                this.attributes["beforeIFrameTpl"] = value;
            }
        }
        
        public object beforeTextAreaTpl
        {
            get
            {
                return this.attributes["beforeTextAreaTpl"];
            }
            set
            {
                this.attributes["beforeTextAreaTpl"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object createLinkText
        {
            get
            {
                return this.attributes["createLinkText"];
            }
            set
            {
                this.attributes["createLinkText"] = value;
            }
        }
        
        public object defaultButtonUI
        {
            get
            {
                return this.attributes["defaultButtonUI"];
            }
            set
            {
                this.attributes["defaultButtonUI"] = value;
            }
        }
        
        public object defaultLinkValue
        {
            get
            {
                return this.attributes["defaultLinkValue"];
            }
            set
            {
                this.attributes["defaultLinkValue"] = value;
            }
        }
        
        public object defaultValue
        {
            get
            {
                return this.attributes["defaultValue"];
            }
            set
            {
                this.attributes["defaultValue"] = value;
            }
        }
        
        public object enableAlignments
        {
            get
            {
                return this.attributes["enableAlignments"];
            }
            set
            {
                this.attributes["enableAlignments"] = value;
            }
        }
        
        public object enableColors
        {
            get
            {
                return this.attributes["enableColors"];
            }
            set
            {
                this.attributes["enableColors"] = value;
            }
        }
        
        public object enableFont
        {
            get
            {
                return this.attributes["enableFont"];
            }
            set
            {
                this.attributes["enableFont"] = value;
            }
        }
        
        public object enableFontSize
        {
            get
            {
                return this.attributes["enableFontSize"];
            }
            set
            {
                this.attributes["enableFontSize"] = value;
            }
        }
        
        public object enableFormat
        {
            get
            {
                return this.attributes["enableFormat"];
            }
            set
            {
                this.attributes["enableFormat"] = value;
            }
        }
        
        public object enableLinks
        {
            get
            {
                return this.attributes["enableLinks"];
            }
            set
            {
                this.attributes["enableLinks"] = value;
            }
        }
        
        public object enableLists
        {
            get
            {
                return this.attributes["enableLists"];
            }
            set
            {
                this.attributes["enableLists"] = value;
            }
        }
        
        public object enableSourceEdit
        {
            get
            {
                return this.attributes["enableSourceEdit"];
            }
            set
            {
                this.attributes["enableSourceEdit"] = value;
            }
        }
        
        public object fontFamilies
        {
            get
            {
                return this.attributes["fontFamilies"];
            }
            set
            {
                this.attributes["fontFamilies"] = value;
            }
        }
        
        public object iframeAttrTpl
        {
            get
            {
                return this.attributes["iframeAttrTpl"];
            }
            set
            {
                this.attributes["iframeAttrTpl"] = value;
            }
        }
        
        public class MultiType_afterIFrameTpl
        {
            
            public @string _string_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_afterTextAreaTpl
        {
            
            public @string _string_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_beforeIFrameTpl
        {
            
            public @string _string_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_beforeTextAreaTpl
        {
            
            public @string _string_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_componentLayout
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_createLinkText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_defaultButtonUI
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_defaultLinkValue
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_defaultValue
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_enableAlignments
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableColors
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableFont
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableFontSize
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableFormat
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableLinks
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableLists
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_enableSourceEdit
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_fontFamilies
        {
            
            public List<string> _List<string>_type;
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_iframeAttrTpl
        {
            
            public @string _string_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
