//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.slider
{
    using System;
    
    
    public partial class Thumb : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _constrain_default = "false";
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object slider
        {
            get
            {
                return this.attributes["slider"];
            }
            set
            {
                this.attributes["slider"] = value;
            }
        }
        
        public class MultiType_constrain
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_slider
        {
            
            public object _System.Object_type;
            
            public object AsExt.slider.MultiSlider
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
