//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container
{
    using System;
    
    
    public partial class Accordion : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.VBox
    {
        
        public string _activeOnTop_default = "false";
        
        public string _align_default = "\'stretch\'";
        
        public string _animate_default = "true";
        
        public string _fill_default = "true";
        
        public string _hideCollapseTool_default = "false";
        
        public string _itemCls_default = "[Ext.baseCSSPrefix + \'box-item\', Ext.baseCSSPrefix + \'accordion-item\']";
        
        public string _multi_default = "false";
        
        public string _titleCollapse_default = "true";
        
        public object activeOnTop
        {
            get
            {
                return this.attributes["activeOnTop"];
            }
            set
            {
                this.attributes["activeOnTop"] = value;
            }
        }
        
        public object align
        {
            get
            {
                return this.attributes["align"];
            }
            set
            {
                this.attributes["align"] = value;
            }
        }
        
        public object animate
        {
            get
            {
                return this.attributes["animate"];
            }
            set
            {
                this.attributes["animate"] = value;
            }
        }
        
        public object autoWidth
        {
            get
            {
                return this.attributes["autoWidth"];
            }
            set
            {
                this.attributes["autoWidth"] = value;
            }
        }
        
        public object collapseFirst
        {
            get
            {
                return this.attributes["collapseFirst"];
            }
            set
            {
                this.attributes["collapseFirst"] = value;
            }
        }
        
        public object fill
        {
            get
            {
                return this.attributes["fill"];
            }
            set
            {
                this.attributes["fill"] = value;
            }
        }
        
        public object hideCollapseTool
        {
            get
            {
                return this.attributes["hideCollapseTool"];
            }
            set
            {
                this.attributes["hideCollapseTool"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object multi
        {
            get
            {
                return this.attributes["multi"];
            }
            set
            {
                this.attributes["multi"] = value;
            }
        }
        
        public object titleCollapse
        {
            get
            {
                return this.attributes["titleCollapse"];
            }
            set
            {
                this.attributes["titleCollapse"] = value;
            }
        }
        
        public class MultiType_activeOnTop
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_align
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_animate
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_autoWidth
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_collapseFirst
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_fill
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_hideCollapseTool
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_itemCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_multi
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_titleCollapse
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
