//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Numeric : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis.Axis
    {
        
        public string _adjustMaximumByMajorUnit_default = "false";
        
        public string _adjustMinimumByMajorUnit_default = "false";
        
        public string _constrain_default = "true";
        
        public string _decimals_default = "2";
        
        public string _position_default = "\'left\'";
        
        public object adjustMaximumByMajorUnit
        {
            get
            {
                return this.attributes["adjustMaximumByMajorUnit"];
            }
            set
            {
                this.attributes["adjustMaximumByMajorUnit"] = value;
            }
        }
        
        public object adjustMinimumByMajorUnit
        {
            get
            {
                return this.attributes["adjustMinimumByMajorUnit"];
            }
            set
            {
                this.attributes["adjustMinimumByMajorUnit"] = value;
            }
        }
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object decimals
        {
            get
            {
                return this.attributes["decimals"];
            }
            set
            {
                this.attributes["decimals"] = value;
            }
        }
        
        public object maximum
        {
            get
            {
                return this.attributes["maximum"];
            }
            set
            {
                this.attributes["maximum"] = value;
            }
        }
        
        public object minimum
        {
            get
            {
                return this.attributes["minimum"];
            }
            set
            {
                this.attributes["minimum"] = value;
            }
        }
        
        public object position
        {
            get
            {
                return this.attributes["position"];
            }
            set
            {
                this.attributes["position"] = value;
            }
        }
        
        public class MultiType_adjustMaximumByMajorUnit
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_adjustMinimumByMajorUnit
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_constrain
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_decimals
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_maximum
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_minimum
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_position
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
