//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy
{
    using System;
    
    
    public partial class JsonP : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy.Server
    {
        
        public string _autoAppendParams_default = "true";
        
        public string _callbackKey_default = "\'callback\'";
        
        public string _recordParam_default = "records";
        
        public object autoAppendParams
        {
            get
            {
                return this.attributes["autoAppendParams"];
            }
            set
            {
                this.attributes["autoAppendParams"] = value;
            }
        }
        
        public object callbackKey
        {
            get
            {
                return this.attributes["callbackKey"];
            }
            set
            {
                this.attributes["callbackKey"] = value;
            }
        }
        
        public object recordParam
        {
            get
            {
                return this.attributes["recordParam"];
            }
            set
            {
                this.attributes["recordParam"] = value;
            }
        }
        
        public class MultiType_autoAppendParams
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_callbackKey
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_recordParam
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
