//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy
{
    using System;
    
    
    public partial class Ajax : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy.Server
    {
        
        public string _binary_default = "false";
        
        public object binary
        {
            get
            {
                return this.attributes["binary"];
            }
            set
            {
                this.attributes["binary"] = value;
            }
        }
        
        public object headers
        {
            get
            {
                return this.attributes["headers"];
            }
            set
            {
                this.attributes["headers"] = value;
            }
        }
        
        public class MultiType_binary
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_headers
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
