//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Line : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Cartesian
    {
        
        public string _fill_default = "false";
        
        public string _markerConfig_default = "{}";
        
        public string _selectionTolerance_default = "20";
        
        public string _showMarkers_default = "true";
        
        public string _smooth_default = "false";
        
        public string _style_default = "{}";
        
        public string _type_default = "\'line\'";
        
        public object fill
        {
            get
            {
                return this.attributes["fill"];
            }
            set
            {
                this.attributes["fill"] = value;
            }
        }
        
        public object markerConfig
        {
            get
            {
                return this.attributes["markerConfig"];
            }
            set
            {
                this.attributes["markerConfig"] = value;
            }
        }
        
        public object selectionTolerance
        {
            get
            {
                return this.attributes["selectionTolerance"];
            }
            set
            {
                this.attributes["selectionTolerance"] = value;
            }
        }
        
        public object showMarkers
        {
            get
            {
                return this.attributes["showMarkers"];
            }
            set
            {
                this.attributes["showMarkers"] = value;
            }
        }
        
        public object smooth
        {
            get
            {
                return this.attributes["smooth"];
            }
            set
            {
                this.attributes["smooth"] = value;
            }
        }
        
        public object style
        {
            get
            {
                return this.attributes["style"];
            }
            set
            {
                this.attributes["style"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public class MultiType_fill
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_markerConfig
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_selectionTolerance
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_showMarkers
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_smooth
        {
            
            public @bool _bool_type;
            
            public @double _double_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_style
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_type
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
