//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.action
{
    using System;
    
    
    public partial class StandardSubmit : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.action.Submit
    {
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public class MultiType_target
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
