//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container
{
    using System;
    
    
    public partial class Border : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.Container
    {
        
        public string _itemCls_default = "[Ext.baseCSSPrefix + \'border-item\', Ext.baseCSSPrefix + \'box-item\']";
        
        public string _splitterResize_default = "true";
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object padding
        {
            get
            {
                return this.attributes["padding"];
            }
            set
            {
                this.attributes["padding"] = value;
            }
        }
        
        public object regionWeights
        {
            get
            {
                return this.attributes["regionWeights"];
            }
            set
            {
                this.attributes["regionWeights"] = value;
            }
        }
        
        public object split
        {
            get
            {
                return this.attributes["split"];
            }
            set
            {
                this.attributes["split"] = value;
            }
        }
        
        public object splitterResize
        {
            get
            {
                return this.attributes["splitterResize"];
            }
            set
            {
                this.attributes["splitterResize"] = value;
            }
        }
        
        public class MultiType_itemCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_padding
        {
            
            public @double _double_type;
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_regionWeights
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_split
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_splitterResize
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
