//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class Observable : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object listeners
        {
            get
            {
                return this.attributes["listeners"];
            }
            set
            {
                this.attributes["listeners"] = value;
            }
        }
        
        public class MultiType_listeners
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
