//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Radar : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Series
    {
        
        public string _showInLegend_default = "false";
        
        public string _style_default = "{}";
        
        public string _type_default = "\"radar\"";
        
        public object markerConfig
        {
            get
            {
                return this.attributes["markerConfig"];
            }
            set
            {
                this.attributes["markerConfig"] = value;
            }
        }
        
        public object showInLegend
        {
            get
            {
                return this.attributes["showInLegend"];
            }
            set
            {
                this.attributes["showInLegend"] = value;
            }
        }
        
        public object showMarkers
        {
            get
            {
                return this.attributes["showMarkers"];
            }
            set
            {
                this.attributes["showMarkers"] = value;
            }
        }
        
        public object style
        {
            get
            {
                return this.attributes["style"];
            }
            set
            {
                this.attributes["style"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object xField
        {
            get
            {
                return this.attributes["xField"];
            }
            set
            {
                this.attributes["xField"] = value;
            }
        }
        
        public object yField
        {
            get
            {
                return this.attributes["yField"];
            }
            set
            {
                this.attributes["yField"] = value;
            }
        }
        
        public class MultiType_markerConfig
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_showInLegend
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_showMarkers
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_style
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_type
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_xField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_yField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
