//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.view
{
    using System;
    
    
    public partial class BoundListKeyNav : zzProject.ExtJSNet.ExtJS.Classes.Ext.util.KeyNav
    {
        
        public object boundList
        {
            get
            {
                return this.attributes["boundList"];
            }
            set
            {
                this.attributes["boundList"] = value;
            }
        }
        
        public class MultiType_boundList
        {
            
            public object _System.Object_type;
            
            public object AsExt.view.BoundList
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
