//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Pie : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Series
    {
        
        public string _angleField_default = "false";
        
        public string _donut_default = "false";
        
        public string _highlightDuration_default = "150";
        
        public string _lengthField_default = "false";
        
        public string _showInLegend_default = "false";
        
        public string _style_default = "{}";
        
        public string _type_default = "\"pie\"";
        
        public object angleField
        {
            get
            {
                return this.attributes["angleField"];
            }
            set
            {
                this.attributes["angleField"] = value;
            }
        }
        
        public object colorSet
        {
            get
            {
                return this.attributes["colorSet"];
            }
            set
            {
                this.attributes["colorSet"] = value;
            }
        }
        
        public object donut
        {
            get
            {
                return this.attributes["donut"];
            }
            set
            {
                this.attributes["donut"] = value;
            }
        }
        
        public object field
        {
            get
            {
                return this.attributes["field"];
            }
            set
            {
                this.attributes["field"] = value;
            }
        }
        
        public object highlightDuration
        {
            get
            {
                return this.attributes["highlightDuration"];
            }
            set
            {
                this.attributes["highlightDuration"] = value;
            }
        }
        
        public object lengthField
        {
            get
            {
                return this.attributes["lengthField"];
            }
            set
            {
                this.attributes["lengthField"] = value;
            }
        }
        
        public object showInLegend
        {
            get
            {
                return this.attributes["showInLegend"];
            }
            set
            {
                this.attributes["showInLegend"] = value;
            }
        }
        
        public object style
        {
            get
            {
                return this.attributes["style"];
            }
            set
            {
                this.attributes["style"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object xField
        {
            get
            {
                return this.attributes["xField"];
            }
            set
            {
                this.attributes["xField"] = value;
            }
        }
        
        public class MultiType_angleField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_colorSet
        {
            
            public List<System.Object> _List<System.Object>_type;
            
            public List<System.Object> AsArray
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
        }
        
        public class MultiType_donut
        {
            
            public @bool _bool_type;
            
            public @double _double_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_field
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_highlightDuration
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_lengthField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_showInLegend
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_style
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_type
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_xField
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
