//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container
{
    using System;
    
    
    public partial class Absolute : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.Anchor
    {
        
        public string _ignoreOnContentChange_default = "true";
        
        public string _itemCls_default = "Ext.baseCSSPrefix + \'abs-layout-item\'";
        
        public object ignoreOnContentChange
        {
            get
            {
                return this.attributes["ignoreOnContentChange"];
            }
            set
            {
                this.attributes["ignoreOnContentChange"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public class MultiType_ignoreOnContentChange
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_itemCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
