//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class BufferStore : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.Store
    {
        
        public string _filterOnLoad_default = "false";
        
        public string _sortOnLoad_default = "false";
        
        public object filterOnLoad
        {
            get
            {
                return this.attributes["filterOnLoad"];
            }
            set
            {
                this.attributes["filterOnLoad"] = value;
            }
        }
        
        public object sortOnLoad
        {
            get
            {
                return this.attributes["sortOnLoad"];
            }
            set
            {
                this.attributes["sortOnLoad"] = value;
            }
        }
        
        public class MultiType_filterOnLoad
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_sortOnLoad
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
