//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.reader
{
    using System;
    
    
    public partial class Reader : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _implicitIncludes_default = "true";
        
        public string _readRecordsOnFailure_default = "true";
        
        public string _root_default = "\'\'";
        
        public string _successProperty_default = "\"success\"";
        
        public string _totalProperty_default = "\"total\"";
        
        public object idProperty
        {
            get
            {
                return this.attributes["idProperty"];
            }
            set
            {
                this.attributes["idProperty"] = value;
            }
        }
        
        public object implicitIncludes
        {
            get
            {
                return this.attributes["implicitIncludes"];
            }
            set
            {
                this.attributes["implicitIncludes"] = value;
            }
        }
        
        public object messageProperty
        {
            get
            {
                return this.attributes["messageProperty"];
            }
            set
            {
                this.attributes["messageProperty"] = value;
            }
        }
        
        public object readRecordsOnFailure
        {
            get
            {
                return this.attributes["readRecordsOnFailure"];
            }
            set
            {
                this.attributes["readRecordsOnFailure"] = value;
            }
        }
        
        public object root
        {
            get
            {
                return this.attributes["root"];
            }
            set
            {
                this.attributes["root"] = value;
            }
        }
        
        public object successProperty
        {
            get
            {
                return this.attributes["successProperty"];
            }
            set
            {
                this.attributes["successProperty"] = value;
            }
        }
        
        public object totalProperty
        {
            get
            {
                return this.attributes["totalProperty"];
            }
            set
            {
                this.attributes["totalProperty"] = value;
            }
        }
        
        public class MultiType_idProperty
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_implicitIncludes
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_messageProperty
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_readRecordsOnFailure
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_root
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_successProperty
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_totalProperty
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
