//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class LruCache : zzProject.ExtJSNet.ExtJS.Classes.Ext.util.HashMap
    {
        
        public object maxSize
        {
            get
            {
                return this.attributes["maxSize"];
            }
            set
            {
                this.attributes["maxSize"] = value;
            }
        }
        
        public class MultiType_maxSize
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
    }
}
