//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class AbstractPanel : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _baseCls_default = "x-panel";
        
        public string _border_default = "true";
        
        public string _componentLayout_default = "\'dock\'";
        
        public string _renderTpl_default = "\'{%this.renderContent(out,values)%}\'";
        
        public string _shrinkWrapDock_default = "false";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object bodyBorder
        {
            get
            {
                return this.attributes["bodyBorder"];
            }
            set
            {
                this.attributes["bodyBorder"] = value;
            }
        }
        
        public object bodyCls
        {
            get
            {
                return this.attributes["bodyCls"];
            }
            set
            {
                this.attributes["bodyCls"] = value;
            }
        }
        
        public object bodyPadding
        {
            get
            {
                return this.attributes["bodyPadding"];
            }
            set
            {
                this.attributes["bodyPadding"] = value;
            }
        }
        
        public object bodyStyle
        {
            get
            {
                return this.attributes["bodyStyle"];
            }
            set
            {
                this.attributes["bodyStyle"] = value;
            }
        }
        
        public object border
        {
            get
            {
                return this.attributes["border"];
            }
            set
            {
                this.attributes["border"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object dockedItems
        {
            get
            {
                return this.attributes["dockedItems"];
            }
            set
            {
                this.attributes["dockedItems"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object shrinkWrapDock
        {
            get
            {
                return this.attributes["shrinkWrapDock"];
            }
            set
            {
                this.attributes["shrinkWrapDock"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_bodyBorder
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_bodyCls
        {
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_bodyPadding
        {
            
            public @double _double_type;
            
            public @string _string_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_bodyStyle
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_border
        {
            
            public @double _double_type;
            
            public @string _string_type;
            
            public @bool _bool_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_componentLayout
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_dockedItems
        {
            
            public object _System.Object_type;
            
            public List<System.Object> _List<System.Object>_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public List<System.Object> AsObject[]
            {
                get
                {
                    return this._List<System.Object>_type;
                }
                set
                {
                    this._List<System.Object>_type = value;
                }
            }
        }
        
        public class MultiType_renderTpl
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public object AsExt.XTemplate
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_shrinkWrapDock
        {
            
            public @bool _bool_type;
            
            public @double _double_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
    }
}
