//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.selection
{
    using System;
    
    
    public partial class Model : zzProject.ExtJSNet.ExtJS.Classes.Ext.util.Observable
    {
        
        public string _pruneRemoved_default = "true";
        
        public string _toggleOnClick_default = "true";
        
        public object allowDeselect
        {
            get
            {
                return this.attributes["allowDeselect"];
            }
            set
            {
                this.attributes["allowDeselect"] = value;
            }
        }
        
        public object mode
        {
            get
            {
                return this.attributes["mode"];
            }
            set
            {
                this.attributes["mode"] = value;
            }
        }
        
        public object pruneRemoved
        {
            get
            {
                return this.attributes["pruneRemoved"];
            }
            set
            {
                this.attributes["pruneRemoved"] = value;
            }
        }
        
        public object toggleOnClick
        {
            get
            {
                return this.attributes["toggleOnClick"];
            }
            set
            {
                this.attributes["toggleOnClick"] = value;
            }
        }
        
        public class MultiType_allowDeselect
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_mode
        {
        }
        
        public class MultiType_pruneRemoved
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_toggleOnClick
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
