//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.resizer
{
    using System;
    
    
    public partial class ResizeTracker : zzProject.ExtJSNet.ExtJS.Classes.Ext.dd.DragTracker
    {
        
        public object constrainTo
        {
            get
            {
                return this.attributes["constrainTo"];
            }
            set
            {
                this.attributes["constrainTo"] = value;
            }
        }
        
        public class MultiType_constrainTo
        {
            
            public object _System.Object_type;
            
            public object _System.Object_type;
            
            public object AsExt.util.Region
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public object AsExt.Element
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
