//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.dd
{
    using System;
    
    
    public partial class DropTarget : zzProject.ExtJSNet.ExtJS.Classes.Ext.dd.DDTarget
    {
        
        public string _dropAllowed_default = "Ext.baseCSSPrefix + \'dd-drop-ok\'";
        
        public string _dropNotAllowed_default = "Ext.baseCSSPrefix + \'dd-drop-nodrop\'";
        
        public string _overClass_default = "\"\"";
        
        public object ddGroup
        {
            get
            {
                return this.attributes["ddGroup"];
            }
            set
            {
                this.attributes["ddGroup"] = value;
            }
        }
        
        public object dropAllowed
        {
            get
            {
                return this.attributes["dropAllowed"];
            }
            set
            {
                this.attributes["dropAllowed"] = value;
            }
        }
        
        public object dropNotAllowed
        {
            get
            {
                return this.attributes["dropNotAllowed"];
            }
            set
            {
                this.attributes["dropNotAllowed"] = value;
            }
        }
        
        public object overClass
        {
            get
            {
                return this.attributes["overClass"];
            }
            set
            {
                this.attributes["overClass"] = value;
            }
        }
        
        public class MultiType_ddGroup
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_dropAllowed
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_dropNotAllowed
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_overClass
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
