//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy
{
    using System;
    
    
    public partial class Proxy : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _batchActions_default = "true";
        
        public string _batchOrder_default = "\'create,update,destroy\'";
        
        public object batchActions
        {
            get
            {
                return this.attributes["batchActions"];
            }
            set
            {
                this.attributes["batchActions"] = value;
            }
        }
        
        public object batchOrder
        {
            get
            {
                return this.attributes["batchOrder"];
            }
            set
            {
                this.attributes["batchOrder"] = value;
            }
        }
        
        public object model
        {
            get
            {
                return this.attributes["model"];
            }
            set
            {
                this.attributes["model"] = value;
            }
        }
        
        public object reader
        {
            get
            {
                return this.attributes["reader"];
            }
            set
            {
                this.attributes["reader"] = value;
            }
        }
        
        public object writer
        {
            get
            {
                return this.attributes["writer"];
            }
            set
            {
                this.attributes["writer"] = value;
            }
        }
        
        public class MultiType_batchActions
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_batchOrder
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_model
        {
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsExt.data.Model
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_reader
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsExt.data.reader.Reader
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_writer
        {
            
            public object _System.Object_type;
            
            public @string _string_type;
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public object AsExt.data.writer.Writer
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
