//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.fx
{
    using System;
    
    
    public partial class Animator : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _delay_default = "0";
        
        public string _duration_default = "250";
        
        public string _dynamic_default = "false";
        
        public string _easing_default = "\'ease\'";
        
        public string _iterations_default = "1";
        
        public object delay
        {
            get
            {
                return this.attributes["delay"];
            }
            set
            {
                this.attributes["delay"] = value;
            }
        }
        
        public object duration
        {
            get
            {
                return this.attributes["duration"];
            }
            set
            {
                this.attributes["duration"] = value;
            }
        }
        
        public object dynamic
        {
            get
            {
                return this.attributes["dynamic"];
            }
            set
            {
                this.attributes["dynamic"] = value;
            }
        }
        
        public object easing
        {
            get
            {
                return this.attributes["easing"];
            }
            set
            {
                this.attributes["easing"] = value;
            }
        }
        
        public object iterations
        {
            get
            {
                return this.attributes["iterations"];
            }
            set
            {
                this.attributes["iterations"] = value;
            }
        }
        
        public object keyframes
        {
            get
            {
                return this.attributes["keyframes"];
            }
            set
            {
                this.attributes["keyframes"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public class MultiType_delay
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_duration
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_dynamic
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_easing
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_iterations
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_keyframes
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_target
        {
            
            public object _System.Object_type;
            
            public object AsExt.fx.target.Target
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
