//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class Number : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.Spinner
    {
        
        public string _allowDecimals_default = "true";
        
        public string _allowExponential_default = "true";
        
        public string _autoStripChars_default = "false";
        
        public string _baseChars_default = "\'0123456789\'";
        
        public string _decimalPrecision_default = "2";
        
        public string _decimalSeparator_default = "\'.\'";
        
        public string _maxText_default = "\'The maximum value for this field is {0}\'";
        
        public string _minText_default = "\'The minimum value for this field is {0}\'";
        
        public string _nanText_default = "\'{0} is not a valid number\'";
        
        public string _negativeText_default = "\'The value cannot be negative\'";
        
        public string _step_default = "1";
        
        public string _submitLocaleSeparator_default = "true";
        
        public object allowDecimals
        {
            get
            {
                return this.attributes["allowDecimals"];
            }
            set
            {
                this.attributes["allowDecimals"] = value;
            }
        }
        
        public object allowExponential
        {
            get
            {
                return this.attributes["allowExponential"];
            }
            set
            {
                this.attributes["allowExponential"] = value;
            }
        }
        
        public object autoStripChars
        {
            get
            {
                return this.attributes["autoStripChars"];
            }
            set
            {
                this.attributes["autoStripChars"] = value;
            }
        }
        
        public object baseChars
        {
            get
            {
                return this.attributes["baseChars"];
            }
            set
            {
                this.attributes["baseChars"] = value;
            }
        }
        
        public object decimalPrecision
        {
            get
            {
                return this.attributes["decimalPrecision"];
            }
            set
            {
                this.attributes["decimalPrecision"] = value;
            }
        }
        
        public object decimalSeparator
        {
            get
            {
                return this.attributes["decimalSeparator"];
            }
            set
            {
                this.attributes["decimalSeparator"] = value;
            }
        }
        
        public object maxText
        {
            get
            {
                return this.attributes["maxText"];
            }
            set
            {
                this.attributes["maxText"] = value;
            }
        }
        
        public object maxValue
        {
            get
            {
                return this.attributes["maxValue"];
            }
            set
            {
                this.attributes["maxValue"] = value;
            }
        }
        
        public object minText
        {
            get
            {
                return this.attributes["minText"];
            }
            set
            {
                this.attributes["minText"] = value;
            }
        }
        
        public object minValue
        {
            get
            {
                return this.attributes["minValue"];
            }
            set
            {
                this.attributes["minValue"] = value;
            }
        }
        
        public object nanText
        {
            get
            {
                return this.attributes["nanText"];
            }
            set
            {
                this.attributes["nanText"] = value;
            }
        }
        
        public object negativeText
        {
            get
            {
                return this.attributes["negativeText"];
            }
            set
            {
                this.attributes["negativeText"] = value;
            }
        }
        
        public object step
        {
            get
            {
                return this.attributes["step"];
            }
            set
            {
                this.attributes["step"] = value;
            }
        }
        
        public object submitLocaleSeparator
        {
            get
            {
                return this.attributes["submitLocaleSeparator"];
            }
            set
            {
                this.attributes["submitLocaleSeparator"] = value;
            }
        }
        
        public class MultiType_allowDecimals
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_allowExponential
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_autoStripChars
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
        
        public class MultiType_baseChars
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_decimalPrecision
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_decimalSeparator
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_maxText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_maxValue
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_minText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_minValue
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_nanText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_negativeText
        {
            
            public @string _string_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_step
        {
            
            public @double _double_type;
            
            public @double AsNumber
            {
                get
                {
                    return this._double_type;
                }
                set
                {
                    this._double_type = value;
                }
            }
        }
        
        public class MultiType_submitLocaleSeparator
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
