//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart
{
    using System;
    
    
    public partial class Mask : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object mask
        {
            get
            {
                return this.attributes["mask"];
            }
            set
            {
                this.attributes["mask"] = value;
            }
        }
        
        public class MultiType_mask
        {
            
            public @bool _bool_type;
            
            public @string _string_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
    }
}
