//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy
{
    using System;
    
    
    public partial class Direct : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.proxy.Server
    {
        
        public string _paramsAsHash_default = "true";
        
        public object api
        {
            get
            {
                return this.attributes["api"];
            }
            set
            {
                this.attributes["api"] = value;
            }
        }
        
        public object directFn
        {
            get
            {
                return this.attributes["directFn"];
            }
            set
            {
                this.attributes["directFn"] = value;
            }
        }
        
        public object extraParams
        {
            get
            {
                return this.attributes["extraParams"];
            }
            set
            {
                this.attributes["extraParams"] = value;
            }
        }
        
        public object paramOrder
        {
            get
            {
                return this.attributes["paramOrder"];
            }
            set
            {
                this.attributes["paramOrder"] = value;
            }
        }
        
        public object paramsAsHash
        {
            get
            {
                return this.attributes["paramsAsHash"];
            }
            set
            {
                this.attributes["paramsAsHash"] = value;
            }
        }
        
        public class MultiType_api
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_directFn
        {
            
            public @string _string_type;
            
            public @string _string_type;
            
            public @string AsFunction
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
        }
        
        public class MultiType_extraParams
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
        
        public class MultiType_paramOrder
        {
            
            public @string _string_type;
            
            public List<string> _List<string>_type;
            
            public @string AsString
            {
                get
                {
                    return this._string_type;
                }
                set
                {
                    this._string_type = value;
                }
            }
            
            public List<string> AsString[]
            {
                get
                {
                    return this._List<string>_type;
                }
                set
                {
                    this._List<string>_type = value;
                }
            }
        }
        
        public class MultiType_paramsAsHash
        {
            
            public @bool _bool_type;
            
            public @bool AsBoolean
            {
                get
                {
                    return this._bool_type;
                }
                set
                {
                    this._bool_type = value;
                }
            }
        }
    }
}
