//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.container
{
    using System;
    
    
    public partial class DockingContainer : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _defaultDockWeights_default = "{top: {render: 1, visual: 1}, left: {render: 3, visual: 5}, right: {render: 5, vi" +
            "sual: 7}, bottom: {render: 7, visual: 3}}";
        
        public object defaultDockWeights
        {
            get
            {
                return this.attributes["defaultDockWeights"];
            }
            set
            {
                this.attributes["defaultDockWeights"] = value;
            }
        }
        
        public class MultiType_defaultDockWeights
        {
            
            public object _System.Object_type;
            
            public object AsObject
            {
                get
                {
                    return this._System.Object_type;
                }
                set
                {
                    this._System.Object_type = value;
                }
            }
        }
    }
}
